name: obmin_flutter
description: Obmin Flutter
version: 0.0.1
homepage: https://github.com/prokhor-andrew/obmin-flutter.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  obmin:
    git:
      url: https://github.com/prokhor-andrew/obmin-dart.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^8.2.0
  flutter_lints: ^6.0.0
  source_gen: ^4.0.1
  build_runner: ^2.8.0
